"""HELP

Revision ID: 1a38ed5d8452
Revises: 
Create Date: 2025-09-19 14:22:31.296495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a38ed5d8452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('given_lunches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_given_lunch_lunch_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('given_lunches', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_given_lunch_lunch_id', 'available_lunches', ['lunch_id'], ['lunch_id'])

    # ### end Alembic commands ###
