"""added picture URL

Revision ID: 3d5acd0f8ecc
Revises: 3dd7826f2100
Create Date: 2025-08-04 21:49:20.657690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5acd0f8ecc'
down_revision = '3dd7826f2100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pictureURL', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('pictureURL')

    # ### end Alembic commands ###
