"""added isAdmin column to students

Revision ID: 5718e7ce4b0a
Revises: ac640546089b
Create Date: 2025-11-14 15:22:59.661827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5718e7ce4b0a'
down_revision = 'ac640546089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###
